[project]
name = "biocutils"
dynamic = [
    "version",
]
description = "Utilities to use across the biocpy packages."
readme = "README.md"
authors = [
    { name = "Jayaram Kancherla", email = "jayaram.kancherla@gmail.com" },
]
requires-python = ">=3.9"
keywords = [
    "bioinformatics",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Typing :: Typed",
]
dependencies = [
    "importlib-metadata>=9.0.0 ; python_full_version < '3.8'",
    "numpy",
]


[project.license]
file = "LICENSE.txt"


[project.urls]
Homepage = "https://github.com/BiocPy/biocutils"
Documentation = "https://biocpy.github.io/biocutils/"
Source = "https://github.com/BiocPy/biocutils"
"Bug Tracker" = "https://github.com/BiocPy/biocutils/issues"

[project.optional-dependencies]
testing = [
    "pandas>=2.0.0",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "scipy",
    "setuptools>=68.0.0",
]

[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.1.0"

[tool.ruff]
line-length = 120
src = [
    "src",
]
exclude = [
    "tests",
    "docs",
]

[tool.ruff.lint]
extend-ignore = [
    "F821",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "E402",
    "F401",
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report term-missing"
testpaths = [
    "tests",
]

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B110"]
